### ISSUE TITLE
'TransformerNetModel_encoder_decoder' object has no attribute 'module'

### ISSUE THREAD

**Issue by agarwalishika** [Yuanhy1997/SeqDiffuSeq#19]
Hi authors, 

Thank you for such a well written repository! Really appreciate researchers like you all.

We are interested in your work and are trying to run your code on our data. However, we are encountering this issue. While we dig into this, could you please also take a look (since you would be more well-versed)?

FWIW, we have not changed anything except the dataloader_utils.py file with code to load in our data.

Thank you!

Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 95, in main
    warmup=args.warmup,
  File "SeqDiffuSeq/trainer.py", line 177, in run_loop
    self.run_step(batch, cond)
  File "SeqDiffuSeq/trainer.py", line 196, in run_step
    self.forward_backward(batch, cond)
  File "SeqDiffuSeq/trainer.py", line 265, in forward_backward
    losses = compute_losses()
  File "SeqDiffuSeq/src/modeling/diffusion/respace.py", line 98, in training_losses
    return super().training_losses(self._wrap_model(model), *args, **kwargs)
  File "SeqDiffuSeq/src/modeling/diffusion/gaussian_diffusion.py", line 376, in training_losses
    x_start_mean = model.model.module.get_embeds(input_ids)
  File ".pyenv/versions/3.7.14/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'TransformerNetModel_encoder_decoder' object has no attribute 'module'

**Comment by agarwalishika** [comment]
Ah never mind - a silly mistake! I didn't put the process on a GPU.
