### ISSUE TITLE
About Inference Problem

### ISSUE THREAD

**Issue by AI7AxonH** [Yuanhy1997/SeqDiffuSeq#26]
Hello! Thanks for your code sharing.
When I run your default inference code:

bash ./inference_scrpts/iwslt_inf.sh path-to-ckpts/ema_0.9999_280000.pt path-to-save-results path-to-ckpts/alpha_cumprod_step_260000.npy

**I met a problem:**

created 6800 samples
sampling complete
Traceback (most recent call last):
  File "inference_main.py", line 210, in <module>
    main()
  File "inference_main.py", line 159, in main
    write_outputs(args=args,
  File "inference_main.py", line 192, in write_outputs
    with open(output_file_basepath, "w") as text_fout:
FileNotFoundError: [Errno 2] No such file or directory: 'path-to-ckpts/ema_0.9999_280000.pt.samples_6750.steps-2000.clamp-no_clamp-normal_10708.txt'

So how I can find the txt file?
I would appreciate it if you can share your idea.

**Comment by Yuanhy1997** [comment]
I think the bug occurs because you have to manually create 'path-to-ckpts' folder in advance. I should have add make directory code.
